package sidebar;

/* Copyright (c) 2010, Johannes Köster <johannes.koester@tu-dortmund.de>
 * All rights reserved.
 *
 * This software is open-source under the BSD license; see "license.txt"
 * for a description.
 */

/*
 * Sidebar.java
 *
 * Created on 25.07.2010, 15:05:01
 */

/**
 *
 * @author Johannes Köster <johannes.koester@tu-dortmund.de>
 */
public class Sidebar extends javax.swing.JPanel {

    /** Creates new form Sidebar */
    public Sidebar() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setBackground(getBackground().darker());
    setLayout(new java.awt.GridBagLayout());
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables

}
