/* Copyright (c) 2010, Johannes Köster <johannes.koester@tu-dortmund.de>
 * All rights reserved.
 *
 * This software is open-source under the BSD license; see "license.txt"
 * for a description.
 */

/*
 * MasterSwitches.java
 *
 * Created on 29.03.2010, 15:45:15
 */
package proteinhypernetwork.tasks.masterSwitches;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import proteinhypernetwork.Controller;

/**
 *
 * @author Johannes Köster <johannes.koester@tu-dortmund.de>
 */
public class MasterSwitchesView extends javax.swing.JPanel {
  

  /** Creates new form MasterSwitches */
  public MasterSwitchesView() {
    initComponents();

    Controller.getInstance().addPropertyChangeListener(new PropertyChangeListener() {

      @Override
      public void propertyChange(PropertyChangeEvent evt) {
        if(evt.getPropertyName().equals(Controller.MASTERSWITCHESPREDICTED))
          masterSwitchesListModel.setMasterSwitches(Controller.getInstance().getMasterSwitches());
      }
    });
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    masterSwitchesListModel = new proteinhypernetwork.tasks.masterSwitches.MasterSwitchesListModel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jList1 = new javax.swing.JList();
    filter = new javax.swing.JTextField();

    setName("Form"); // NOI18N

    jScrollPane1.setName("jScrollPane1"); // NOI18N

    jList1.setModel(masterSwitchesListModel);
    jList1.setName("jList1"); // NOI18N
    jScrollPane1.setViewportView(jList1);

    org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(proteinhypernetwork.ProteinHypernetworkApp.class).getContext().getResourceMap(MasterSwitchesView.class);
    filter.setText(resourceMap.getString("filter.text")); // NOI18N
    filter.setToolTipText(resourceMap.getString("filter.toolTipText")); // NOI18N
    filter.setName("filter"); // NOI18N
    filter.setPreferredSize(new java.awt.Dimension(200, 28));
    filter.putClientProperty("JTextField.variant", "search");
    filter.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        filterMouseClicked(evt);
      }
    });
    filter.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        filterActionPerformed(evt);
      }
    });
    filter.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        filterFocusGained(evt);
      }
      public void focusLost(java.awt.event.FocusEvent evt) {
        filterFocusLost(evt);
      }
    });

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .add(filter, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
      .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(filter, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterActionPerformed
    org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(proteinhypernetwork.ProteinHypernetworkApp.class).getContext().getResourceMap(MasterSwitchesView.class);
    if(!filter.getText().equals(resourceMap.getString("filter.text")))
      masterSwitchesListModel.filter(filter.getText());
  }//GEN-LAST:event_filterActionPerformed

  private void filterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filterMouseClicked
    
  }//GEN-LAST:event_filterMouseClicked

  private void filterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_filterFocusGained
    if(filter.getText().equals(org.jdesktop.application.Application.getInstance(
            proteinhypernetwork.ProteinHypernetworkApp.class).getContext().getResourceMap(
            MasterSwitchesView.class).getString("filter.text")))
      filter.setText("");
  }//GEN-LAST:event_filterFocusGained

  private void filterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_filterFocusLost
    if(!masterSwitchesListModel.isFiltered())
      filter.setText(org.jdesktop.application.Application.getInstance(
            proteinhypernetwork.ProteinHypernetworkApp.class).getContext().getResourceMap(
            MasterSwitchesView.class).getString("filter.text"));
  }//GEN-LAST:event_filterFocusLost

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField filter;
  private javax.swing.JList jList1;
  private javax.swing.JScrollPane jScrollPane1;
  private proteinhypernetwork.tasks.masterSwitches.MasterSwitchesListModel masterSwitchesListModel;
  // End of variables declaration//GEN-END:variables
}
